# Addon manifest file
schema_version = "1.0.0"

id = "ndptools"

version = "1.0.2"

name = "NDPTools: General clean up tools"

tagline = "Adds a panel with tools for cleaning up objects, data, nodes and more."

maintainer = "NDP <@ndp>"

type = "add-on"

website = "https://github.com/SleepyEngi/NDPTools"

tags = ["Scene","User Interface"]

blender_version_min = "4.2.0"
# blender_version_max = "5.1.0"

license = ["SPDX:GPL-3.0-or-later",]

# platforms = ["windows-x64", "macos-arm64", "linux-x64"]

[permissions]
files = "Imports 'hair curve profile' node from default Blender assets"